# Use the official Node.js image as the base image
FROM node:20

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy the package.json and yarn.lock files to the working directory
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Expose the port the app runs on
EXPOSE 3001

# Define the command to run the application in development mode
CMD ["yarn", "start:dev"]