version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - '$PORT:$PORT'
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_ADMIN
      - POSTGRES_PASSWORD=$DB_ADMIN_PWD
      - POSTGRES_DB=$DB_NAME
    ports:
      - '$DB_PORT:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2.3
    container_name: redis
    restart: unless-stopped
    env_file: .env
    ports:
      - '$REDIS_PORT:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - cache:/data

volumes:
  dbdata:
    driver: local
  cache:
    driver: local
