version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_USER_PWD: ${DB_USER_PWD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      BROKER_BASIC_USERNAME: ${BROKER_BASIC_USERNAME}
      BROKER_BASIC_PASSWORD: ${BROKER_BASIC_PASSWORD}
      BROKER_BEARER_IDENTITIES: ${BROKER_BEARER_IDENTITIES}
      DASHBOARD_URL: ${DASHBOARD_URL}
      CORS_URL: ${CORS_URL}
      TZ: ${TZ}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
