export enum ServiceInstanceStatus {
  ACTIVE = 'ACTIVE',
  FAILED = 'FAILED',
  PROCESSING = 'PROCESSING',
  DEPLOYING = 'DEPLOYING',
  DISABLED = 'DISABLED',
  DEPROVISIONING = 'DEPROVISIONING',
  DEPROVISIONED = 'DEPROVISIONED',
}
